### ISSUE TITLE
Concurrency high CPU and slow performance  

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimi#113]
When running concurrently for in my case pinging 20 servers with concurrency of 20 the platform seems to increase CPU to a high level and also result in poor performance.  It is faster to run it without concurrency how can this be?

![image](https://user-images.githubusercontent.com/81556695/114164900-c0a6e400-9923-11eb-8672-fb340f0a3f5c.png)

![image](https://user-images.githubusercontent.com/81556695/114164930-c7355b80-9923-11eb-811f-f13b47b5671a.png)

**Comment by z1pti3** [comment]
Recreated the issue by setting up a threaded trigger with 5 concurrency and 10 events:

![image](https://user-images.githubusercontent.com/66521110/115108498-ba8ab600-9f68-11eb-98e4-dd2b6ae3447f.png)
 

It looks like the bug is due to threaded mode disabling cpuSaver to speed up execution and  so that the maximum performance can be gained.

Within trigger.py

![image](https://user-images.githubusercontent.com/66521110/115108552-105f5e00-9f69-11eb-8d83-33648fa7b829.png)

**Comment by z1pti3** [comment]
Retested with the latest push and CPU is now stable
