### ISSUE TITLE
[Bug] secret storage does not work for non-admins

### ISSUE THREAD

**Issue by u-n-i-c-o-rn** [z1pti3/jimi#259]
secret storage does not work for non-admins when adding an item nothing happens

**Comment by b1scuit-thi3f** [comment]
After further testing I believe this was user error. We did check if the user could actually use some of the menu items (storage, secrets, admin) but this has now been fixed with f5e2336fcdef98ef6e598cdfb1fa2c3a8dd74bf0.
Users that are not added to the model will now no longer see secrets, storage or admin unless added to in the model editor or becomes a member of the administrators group.
