### ISSUE TITLE
GUI - Status Page Suggestions

### ISSUE THREAD

**Issue by b1scuit-thi3f** [z1pti3/jimi#87]
Status page is really nice, but we should look at a few nice looking options:

- Hide/Show Disabled Triggers
- Group By Cluster

I may add more here before I sort these out.

**Comment by b1scuit-thi3f** [comment]
Added the initial for this with https://github.com/z1pti3/jimi/commit/93df47eda374404a97c43107a81eb784a57b932d, but could do with some neatening up

**Comment by b1scuit-thi3f** [comment]
More suggestions:

- Right click context menu - allows for quick view of trigger, restart option etc
- Double-click to navigate to trigger

**Comment by z1pti3** [comment]
Added double click to open conduct for given trigger in new tab. b7342953007846d4d03dd4cb48bd980afc9c4eae

**Comment by b1scuit-thi3f** [comment]
Beat me to it ;) 
I think it might be nice to have some sort of zoom or highlight function so the user can identify the trigger quickly once the conduct has loaded. Perhaps the conduct editor needs a highlight function?

**Comment by z1pti3** [comment]
Updated status page to include system splitting as it did before. 

Right click context menu is also now included and has option to reset trigger.

Disabled triggers no longer shown.

Zoom option in future would be nice but maybe a future request? At the moment you can see which triggers have failed because they show as red which is the main purpose of the panel on the status page anyway?
